#!/usr/bin/env bash
# LLM Orchestrator installer / verifier.
# Usage:
#   ./scripts/install.sh --check         verify the local checkout is sane
#   ./scripts/install.sh --link          symlink into ~/.claude/llm-orchestrator
#   ./scripts/install.sh --copy <dir>    copy skills/commands/templates into <dir>/.claude/

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

cmd="${1:-}"
case "${cmd}" in
  --check)
    fail=0
    for f in README.md AGENTS.md CLAUDE.md concise-agent-protocol.md ARCHITECTURE.md \
             .claude-plugin/plugin.json .claude-plugin/marketplace.json hooks/hooks.json; do
      if [[ ! -f "${ROOT}/${f}" ]]; then
        echo "missing: ${f}"; fail=1
      fi
    done
    for d in skills commands agents templates hooks scripts/hooks scripts/lib output-styles docs examples tests config; do
      if [[ ! -d "${ROOT}/${d}" ]]; then
        echo "missing dir: ${d}"; fail=1
      fi
    done
    # Required hook scripts
    for f in scripts/hooks/session-start.sh scripts/hooks/user-prompt-submit.sh scripts/hooks/guard-no-verify.sh scripts/hooks/guard-destructive-git.sh scripts/hooks/subagent-stop.sh scripts/hooks/orch-stop.sh scripts/hooks/orch-handoff-nudge.sh scripts/hooks/orch-verify-gate.sh scripts/hooks/orch-retry-cap.sh scripts/hooks/orch-evidence-ledger.sh scripts/hooks/orch-worktree-reaper.sh scripts/lib/orch-lock.sh scripts/lib/orch-protocol.sh scripts/lib/orch-handoff.sh scripts/lib/orch-project.sh scripts/lib/orch-signals.sh scripts/lib/orch-evidence.sh scripts/lib/orch-detect.sh scripts/orch-worktree-materialize.sh scripts/orch-worktree-integrate.sh scripts/hooks/orch-protocol-grader.sh scripts/hooks/orch-research-gate.sh scripts/hooks/orch-researcher-validator.sh scripts/statusline.sh scripts/protocol-lint.sh output-styles/orchestrator.md; do
      if [[ ! -f "${ROOT}/${f}" ]]; then
        echo "missing: ${f}"; fail=1
      fi
    done
    # Every skill must have SKILL.md
    while IFS= read -r dir; do
      if [[ ! -f "${dir}/SKILL.md" ]]; then
        echo "missing SKILL.md in: ${dir}"; fail=1
      fi
    done < <(find "${ROOT}/skills" -mindepth 1 -maxdepth 1 -type d)

    if [[ ${fail} -eq 0 ]]; then
      echo "LLM Orchestrator check: OK"
    else
      echo "LLM Orchestrator check: FAILED"
      exit 1
    fi
    ;;

  --link)
    target="${HOME}/.claude/llm-orchestrator"
    mkdir -p "$(dirname "${target}")"
    if [[ -e "${target}" || -L "${target}" ]]; then
      echo "target already exists: ${target}"; exit 1
    fi
    ln -s "${ROOT}" "${target}"
    echo "Linked ${ROOT} -> ${target}"
    ;;

  --copy)
    dest="${2:-}"
    if [[ -z "${dest}" ]]; then
      echo "usage: $0 --copy <project-dir>"; exit 1
    fi
    if [[ ! -d "${dest}" ]]; then
      echo "no such directory: ${dest}"; exit 1
    fi
    mkdir -p "${dest}/.claude" "${dest}/.claude/scripts/hooks" "${dest}/.claude/scripts/lib"
    cp -R "${ROOT}/skills" "${dest}/.claude/"
    cp -R "${ROOT}/commands" "${dest}/.claude/"
    cp -R "${ROOT}/templates" "${dest}/.claude/"
    cp -R "${ROOT}/agents" "${dest}/.claude/" 2>/dev/null || true
    cp -R "${ROOT}/output-styles" "${dest}/.claude/" 2>/dev/null || true
    cp -R "${ROOT}/hooks" "${dest}/.claude/"
    # Copy hook scripts and statusline.
    for f in "${ROOT}/scripts/hooks/"*.sh; do
      [[ -f "${f}" ]] && cp "${f}" "${dest}/.claude/scripts/hooks/"
    done
    [[ -f "${ROOT}/scripts/statusline.sh" ]] && cp "${ROOT}/scripts/statusline.sh" "${dest}/.claude/scripts/"
    [[ -f "${ROOT}/scripts/protocol-lint.sh" ]] && cp "${ROOT}/scripts/protocol-lint.sh" "${dest}/.claude/scripts/"
    [[ -f "${ROOT}/scripts/orch-worktree-materialize.sh" ]] && cp "${ROOT}/scripts/orch-worktree-materialize.sh" "${dest}/.claude/scripts/"
    [[ -f "${ROOT}/scripts/orch-worktree-integrate.sh" ]] && cp "${ROOT}/scripts/orch-worktree-integrate.sh" "${dest}/.claude/scripts/"
    # Copy the portable lock helper — memory commands source it.
    for f in "${ROOT}/scripts/lib/"*.sh; do
      [[ -f "${f}" ]] && cp "${f}" "${dest}/.claude/scripts/lib/"
    done
    # Copy the protocol doc so the meta-skill's relative link resolves.
    cp "${ROOT}/concise-agent-protocol.md" "${dest}/.claude/" 2>/dev/null || true

    sed_inplace() {
      if sed --version >/dev/null 2>&1; then
        sed -i "$@"  # GNU
      else
        sed -i '' "$@"  # BSD/macOS
      fi
    }
    # Rewrite hook paths so they resolve without CLAUDE_PLUGIN_ROOT.
    sed_inplace "s|\$CLAUDE_PLUGIN_ROOT|${dest}/.claude|g" "${dest}/.claude/hooks/hooks.json"

    # Generate a starter settings.json. We do NOT auto-embed the plugin's
    # hooks.json — its schema differs from settings.json's hooks schema and
    # would silently fail to fire. Instead, document the wiring step.
    if [[ ! -f "${dest}/.claude/settings.json" ]]; then
      cat > "${dest}/.claude/settings.json" <<'EOF'
{
  "_note": "Generated by LLM Orchestrator install.sh --copy. To enable the hooks, see the 'Wiring hooks' section in docs/install.md — Claude Code's settings.json hook format differs from the plugin format, so we don't auto-embed.",
  "env": {
    "ORCH_HOOK_PROFILE": "standard"
  }
}
EOF
    fi
    echo "Copied LLM Orchestrator into ${dest}/.claude/"
    echo "Hook paths rewritten to absolute."
    echo "Set ORCH_HOME if you want memory in a different location (defaults to ~/.llm-orchestrator)."
    echo
    echo "NEXT STEP: to fire hooks, either install as a Claude Code plugin OR"
    echo "          add the hook entries to ${dest}/.claude/settings.json — see docs/install.md."
    ;;

  *)
    cat <<USAGE
LLM Orchestrator installer

  $0 --check                verify the local checkout is sane
  $0 --link                 symlink this repo into ~/.claude/llm-orchestrator
  $0 --copy <project-dir>   copy into <project-dir>/.claude/
USAGE
    exit 1
    ;;
esac
